version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: qp_db
      POSTGRES_USER: qp_user
      POSTGRES_PASSWORD: qp_db_123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_URL = postgres://qp_user:qp_db_123@db:5432/qp_db
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
